server:
  port: 80
  servlet:
    context-path: /

spring:
  messages:
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.94.81.127:3306/hyzj?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: hyzjdba
    password: hyzjprogroup
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/, classpath:/templates/
#
#  mvc:
#    static-path-pattern: /**